### ISSUE TITLE
New custom metrics functionality

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#236]
After talking today with @jservonnat we discussed a clearer path forward for custom metrics.. On a 1.1, 1.5, 2.0 release timeline..  Considering changes in milestones:

Stage 1 - 1.1 milestone timeline (using current obs/model seasonal climatologies):
- [ ] Add new variables (@jservonnat has tested this for jet latitude - should this be included in standard suite?)
- [x] Add new obs through custom obs dictionary (@doutriaux has fixed with #244)
- [ ] Handling multiple custom metrics through a new dictionary (@doutriaux has proposed fix #243 in response to #220)
- [ ] Pass complete variable name to compute_metrics (#229, #240)
- [ ] Add variable to JSON output file (#226)
- [ ] Append info for default and custom_metrics at bottom of JSON file (#221)

Stage 2 - 1.5 milestone timeline:
- [ ] Using regional masks (land surface - vegetation) ; consider interactions with [ILAMB](http://ilamb.org/) - IPSL will provide rapid feedback on this, they want to do this now with IPSL output (Note interpolation with integer vegetation zones will not work here)

Stage 3 - 2.0 milestone timeline (new input data formats):
- [ ] Using timeseries inputs (obs/models)
- [ ] Working with native grid data (as above, land-surface and also ocean transports etc when interpolation doesn't make sense..)

It's likely there is some interaction with the list above and #87, #219, #232

**Comment by doutriaux1** [comment]
I think for 2.0, we should switch the obs to an esgf-served format. Should we create an issue for this?

**Comment by jservonnat** [comment]
I forgot those points:
- [] handling multiple custom compute_metrics functions (related with #220)
- [] pass the complete variable name to the compute_metrics function (#229)
- [] provide detailed information about the calculated metrics at the bottom of the json file (#221)

**Comment by jservonnat** [comment]
For you guys @doutriaux1 @durack1 @gleckler1: after the development (currently in test) of the metric on the latitude of the jets I would like to move on with metrics on sea ice and some others on the ocean. However, there is quickly the need to use multiple variables (for example, to calculate the sea ice volume). Also, that would be better to do those computations on the native grid.
I would be happy to help on the development of a version of the Metrics Package that could do all those things (in parallel of the official, working version). So here is my point: are you guys ready to start working on those functionalities (pretty much stage 3 of the milestones defined by @durack1 above) or you prefer to leave it for later on? If you are at least ready to discuss about the ways those functionalities can be developed, I'll be happy to put my hands in the code to try to implement them.
Let me know!
